murl: main.o dict.o shorties.o
	gcc -o murl main.o dict.o shorties.o

dict.o: dict.c
	gcc -c -o dict.o dict.c

shorties.o: shorties.c
	gcc -c -o shorties.o shorties.c

main.o: main.c
	gcc -c -o main.o main.c