name: Build and publish container image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the container image
        run: docker build . --file Containerfile --tag murl:$(date +%s)

      - name: Login to ghcr
        run: docker login ghcr.io  -u Sencyy --password ${{secrets.PACKAGES_TOKEN}}

      - name: Publish image to ghcr
        run: docker push ghcr.io/sencyy/murl:latest